.TH gnome-split 1 "August 2011" "GNOME Split manpage" "User commands"
.SH NAME
GNOME Split \- File splitter for GNOME desktop
.SH SYNOPSIS
gnome-split [OPTION] [FILE]
.SH DESCRIPTION
GNOME Split is a tool that allows you to split files and merge them back. It is
written in Java and uses a GTK+ user interface (thanks to the java-gnome
project). The goal is to offer a native implementation of similar projects which
can handle multiple file formats (e.g. Xtremsplit).
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-split\fR
display the split view
.TP
\fB\-m\fR, \fB\-\-merge\fR
display the merge view
.SH BUGS
Oh right, just go check them https://bugs.launchpad.net/gnome-split
.SH AUTHOR
Written by Guillaume Mazoyer
